
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://vfxvvovudyaofgdbkfua.supabase.co';
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeHZ2b3Z1ZHlhb2ZnZGJrZnVhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzIzNzc0NSwiZXhwIjoyMDgyODEzNzQ1fQ.gcsL6ezXgphSzlMY47IgQI2glPqJD5prHdFhXRq05d0';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const quests = [
    { id: '53b01a3d-065d-4a1c-95be-93778f305b49', content: 'Read 5 pages of a book (any book)', reflection_prompt: 'What was the main idea or takeaway?', target_archetype: 'Certified Brain Rotter' },
    { id: '1c59e98b-8d3a-4f2b-a28e-de648b400880', content: 'Take a 10-minute walk outside without your phone', reflection_prompt: 'How did you feel during the walk?', target_archetype: 'Certified Brain Rotter' },
    { id: '480c97bd-45b5-4ab9-952d-585cbaaf1ba5', content: 'Write down 3 things you\'re grateful for', reflection_prompt: 'Why are these things meaningful to you?', target_archetype: 'Certified Brain Rotter' },
    { id: 'c7140563-d204-4543-b3b3-41d281812721', content: 'One-App Productivity Sprint', reflection_prompt: 'Reflect on how completing "One-App Productivity Sprint" helped you. For a focused 30-minute block, choose one essential task that requires a specific app (e.g., email, document editing). Close all other applications and notifications. This hones your concentration and reduces digital distractions.', target_archetype: 'Focus Initiator' },
    { id: '59efed71-1ab0-42a3-b95f-14709ed950a6', content: 'The 10-Minute Tech Break', reflection_prompt: 'Reflect on how completing "The 10-Minute Tech Break" helped you. Take a mindful break from all screens for at least 10 consecutive minutes. Use this time to stretch, look out a window, or simply sit in silence. Notice how you feel after this brief digital detox.', target_archetype: 'Mind Wanderer' },
    { id: '1aa6180b-d763-40c8-829f-da579162a632', content: 'Audio Immersion', reflection_prompt: 'Reflect on how completing "Audio Immersion" helped you. Replace one screen-based activity (e.g., social media scrolling) with an engaging audio experience for at least 30 minutes. This could be a podcast, audiobook, or a new music album. Focus on truly listening without distractions.', target_archetype: 'Mind Wanderer' },
    { id: '6d0756a0-8fa8-419c-ae16-bd9adda8a691', content: 'Screen-Free Commute', reflection_prompt: 'Reflect on how completing "Screen-Free Commute" helped you. If you commute, dedicate your entire journey to being screen-free. Observe your surroundings, listen to an audiobook or podcast, or simply relax your mind without digital input.', target_archetype: 'Mind Wanderer' },
    { id: 'd42d54e1-58c2-4e0d-a98e-5194d468aee2', content: 'Plan Tomorrow Offline', reflection_prompt: 'Reflect on how completing "Plan Tomorrow Offline" helped you. Spend 10 minutes planning your next day\'s tasks, appointments, or goals using only pen and paper. Avoid using any digital devices during this planning session.', target_archetype: 'Mind Wanderer' },
    { id: '22ba897b-3dcc-4c68-869e-d7dcd9018a8a', content: 'Single-Task Session: 40-Min Deep Dive', reflection_prompt: 'Reflect on how completing "Single-Task Session: 40-Min Deep Dive" helped you. Choose one important task and dedicate 40 minutes of uninterrupted work to it. Silence notifications and put your phone away. Focus solely on completing as much of this single task as possible.', target_archetype: 'Focus Initiator' },
    { id: '5565ed04-358b-483a-9bcd-48971e3f1111', content: 'The 3-Minute Reset: Do a sensory check-in. Notice 5 things you can see, 4 things you can feel, 3 things you can hear, 2 things you can smell, and 1 thing you can taste. This grounding technique pulls your mind out of anxiety spirals.', reflection_prompt: 'Today, I give myself permission to just start. What did you notice during your sensory check-in?', target_archetype: 'Certified Brain Rotter' },
    { id: 'c2a6a2d0-b7af-48fb-8b40-26bdca662bdd', content: 'Pomodoro Power Start: 25-Min Focus', reflection_prompt: 'Reflect on how completing "Pomodoro Power Start: 25-Min Focus" helped you. Set a timer for 25 minutes and commit to working on one high-priority task without interruptions. Take a 5-minute break afterwards. This helps build sustained focus.', target_archetype: 'Focus Initiator' },
    { id: 'd9928e91-6a25-40ca-afd5-697df6c96980', content: 'Analog Planning Power-Up', reflection_prompt: 'Reflect on how completing "Analog Planning Power-Up" helped you. Spend 15-20 minutes planning your top 3 productive tasks for tomorrow using a physical notebook or planner. This helps you prioritize and mentally prepare, reducing reliance on digital tools for initial planning.', target_archetype: 'Focus Initiator' },
    { id: 'ca9deaaf-eebc-4291-a7ca-8be613ac98cb', content: 'The \'Productivity Audit\' Session', reflection_prompt: 'Reflect on how completing "The \'Productivity Audit\' Session" helped you. For 30 minutes, review your last week\'s productivity. Identify your most productive times and common distractions. Use these insights to plan your next day for maximum focus and efficiency.', target_archetype: 'Focus Initiator' },
    { id: '9f738868-f741-4936-a406-62aebb0d0d5b', content: 'The Single-Task Sprint', reflection_prompt: 'Reflect on how completing "The Single-Task Sprint" helped you. Choose one specific task that requires your full attention. Set a timer for 30 minutes and work on only that task, keeping your phone on \'do not disturb\' and out of sight. Resist the urge to switch tasks or check notifications.', target_archetype: 'Balanced Thinker' },
    { id: 'e04f98f1-f43a-49f7-8ab2-61a05f001bf5', content: 'One-Page Paper Planner', reflection_prompt: 'Reflect on how completing "One-Page Paper Planner" helped you. Dedicate 15 minutes to sketching out your priorities and tasks for tomorrow on a single sheet of paper. Focus on broad strokes rather than minute details, allowing for flexibility.', target_archetype: 'Mind Wanderer' },
    { id: '80c15bf1-54ff-47fe-af98-4e57e92ee04d', content: 'Ambient Soundscape Discovery', reflection_prompt: 'Reflect on how completing "Ambient Soundscape Discovery" helped you. Spend 15 minutes listening to a non-digital ambient soundscape (e.g., nature sounds, instrumental music, or the sounds of your environment). Notice how different sounds impact your mood and focus.', target_archetype: 'Mind Wanderer' },
    { id: '9b8da94a-3db8-40c2-9e19-6294f0ae0d7e', content: 'Digital Declutter: Notification Audit', reflection_prompt: 'Reflect on how completing "Digital Declutter: Notification Audit" helped you. Spend 15 minutes reviewing your phone\'s notification settings. Turn off non-essential notifications for apps that frequently interrupt your focus. Prioritize what truly needs your immediate attention.', target_archetype: 'Balanced Thinker' },
    { id: 'db07612d-89e1-44b1-8e07-52434254a264', content: 'Focus Fuel: Mindful Movement Break', reflection_prompt: 'Reflect on how completing "Focus Fuel: Mindful Movement Break" helped you. Integrate a short 5-10 minute mindful movement break into your day, away from your screen. This could be stretching, a quick walk, or light yoga. Notice how it refreshes your mind and body for better focus.', target_archetype: 'Balanced Thinker' },
    { id: '2a26e09d-58ad-4c87-adb7-27ba28191e59', content: 'Deep Work Prep: Environment Scan', reflection_prompt: 'Reflect on how completing "Deep Work Prep: Environment Scan" helped you. Before starting a focused work session, take 5 minutes to scan your physical environment. Remove any visual or auditory distractions, tidy your workspace, and ensure you have everything you need close at hand. This sets the stage for productive focus.', target_archetype: 'Balanced Thinker' },
    { id: '3ce2ce97-130d-478b-88dd-f7df66c018ea', content: 'Offline Brainstorm Block', reflection_prompt: 'Reflect on how completing "Offline Brainstorm Block" helped you. Set aside 45 minutes to brainstorm ideas or plan a project using only pen and paper. Experience the clarity and focus that comes from disconnecting from digital tools for a specific task.', target_archetype: 'Focus Initiator' },
    { id: '57df8a54-ff81-4928-8bf7-0e541f38de02', content: 'Dedicated Deep Work Block', reflection_prompt: 'Reflect on how completing "Dedicated Deep Work Block" helped you. Set a timer for 25 minutes and dedicate this time to a single, focused task without any digital distractions. Put your phone away and close unnecessary tabs. Afterward, take a 5-minute break.', target_archetype: 'Mind Wanderer' },
    { id: '1f42ccf6-dc3d-45b0-805a-82dbd3779dd8', content: 'Sensory Reset Walk: 15 Minutes Outdoors', reflection_prompt: 'Reflect on how completing "Sensory Reset Walk: 15 Minutes Outdoors" helped you. Take a 15-minute walk outside with the intention of focusing on your five senses. Notice the sounds, sights, smells, and textures around you, without your phone. This helps to ground you and shift your attention away from screens.', target_archetype: 'Mind Wanderer' },
    { id: '6de56c80-e6e6-492e-928a-35934c912ebf', content: 'Connect with Nature: 15-Minute Stroll', reflection_prompt: 'Reflect on how completing "Connect with Nature: 15-Minute Stroll" helped you. Step outside for at least 15 minutes and consciously observe the natural world around you. Leave your phone behind or keep it on silent in your pocket.', target_archetype: 'Mind Wanderer' },
    { id: '651b51ec-6a5b-4320-90f8-f9103d7eb2d4', content: 'Watch an educational video instead of scrolling', reflection_prompt: 'What new thing did you learn?', target_archetype: 'Balanced Thinker' },
    { id: 'c01dc5c1-e11b-45ce-8a70-301af02a25e6', content: 'Nature\'s Scroll', reflection_prompt: 'Reflect on how completing "Nature\'s Scroll" helped you. Instead of scrolling through your phone, take a 15-minute walk outside and mindfully observe your surroundings. Pay attention to the sights, sounds, and smells without any digital distractions. This offers a refreshing break and reduces passive screen exposure.', target_archetype: 'Focus Initiator' },
    { id: 'b3aa3969-8641-4073-be4f-4c3a160eee5d', content: 'The Tech-Free Morning Hour', reflection_prompt: 'Reflect on how completing "The Tech-Free Morning Hour" helped you. Start your day with a screen-free hour. Before checking any devices, engage in an activity like reading a physical book, light stretching, or enjoying your breakfast mindfully. This helps establish a calm and focused tone for your day.', target_archetype: 'Focus Initiator' },
    { id: '67873e11-c18d-4a4f-beac-231618c79156', content: 'Screen-Free Zone Challenge', reflection_prompt: 'Reflect on how completing "Screen-Free Zone Challenge" helped you. Designate one specific area in your home as a \'screen-free zone\' for the entire day (e.g., the dining table, a specific armchair). Commit to not using any digital devices while in this area.', target_archetype: 'Mind Wanderer' },
    { id: 'c851b191-f434-47d0-9942-f5a47754aa1e', content: 'App-Free Morning Start', reflection_prompt: 'Reflect on how completing "App-Free Morning Start" helped you. For the first 30 minutes after waking up, avoid opening any apps on your phone or computer. Instead, focus on a non-digital activity like making coffee, reading a physical book, or planning your day.', target_archetype: 'Mind Wanderer' },
    { id: '337ad342-8693-4ba2-9b82-0c8e7a729ad3', content: 'Focused Learning Block', reflection_prompt: 'Reflect on how completing "Focused Learning Block" helped you. Commit 60 minutes to learning a new skill or topic using a single, dedicated resource (e.g., a book, an online course module on a single tab). Eliminate all other digital distractions for this hour. This builds sustained attention for learning.', target_archetype: 'Focus Initiator' },
    { id: '348b29a7-c154-4bf6-95d0-ac9837c77411', content: 'Read a Physical Book for 15 Min', reflection_prompt: 'Reflect on how completing "Read a Physical Book for 15 Min" helped you. Pick up a physical book, magazine, or newspaper and read for at least 15 minutes. Engage with a tangible story or article without the distractions of a digital screen.', target_archetype: 'Mind Wanderer' },
    { id: '2a460034-f354-4f52-8652-4f947832a77a', content: 'Pre-Work Prep: 15-Min Digital Declutter', reflection_prompt: 'Reflect on how completing "Pre-Work Prep: 15-Min Digital Declutter" helped you. Before starting your main work, spend 15 minutes organizing your digital workspace. Close unnecessary tabs, clear your desktop, and organize files to create a distraction-free environment for improved focus.', target_archetype: 'Focus Initiator' },
    { id: '108f00de-91ed-4e3f-85fc-570d307cd9ea', content: 'Email Triage & Unsubscribe Blitz', reflection_prompt: 'Reflect on how completing "Email Triage & Unsubscribe Blitz" helped you. Dedicate 20 minutes to quickly process your inbox. Delete unnecessary emails, respond to urgent ones, and unsubscribe from 3-5 newsletters that no longer serve your productivity goals.', target_archetype: 'Focus Initiator' },
    { id: '568e66f5-7979-45a8-a46d-8832747ac55f', content: 'The \'Deep Dive\' Focus Block', reflection_prompt: 'Reflect on how completing "The \'Deep Dive\' Focus Block" helped you. Dedicate a distraction-free 45-minute block to a single productive task. Close all unnecessary tabs and apps, and silence notifications to maximize your concentration. This quest helps build sustained focus.', target_archetype: 'Focus Initiator' },
    { id: 'e04c1776-8da9-41f3-9fe8-a9f2c7924183', content: 'Productivity Power Hour: Focused Sprint', reflection_prompt: 'Reflect on how completing "Productivity Power Hour: Focused Sprint" helped you. Choose one specific task you need to complete and dedicate a full 60 minutes of uninterrupted, focused work to it. Turn off all notifications and eliminate distractions. Log your progress and celebrate your focused effort.', target_archetype: 'Focus Initiator' },
    { id: 'fc53ad4c-8018-4923-995a-d6ff2b84c5e6', content: 'Mindful Morning Pages', reflection_prompt: 'Reflect on how completing "Mindful Morning Pages" helped you. Dedicate 15 minutes each morning for the next three days to free-form journaling with pen and paper. No screens allowed until this task is complete.', target_archetype: 'Focus Initiator' },
    { id: 'aff61672-3908-4d54-a438-c403a17e9b6b', content: 'Sensory Scavenger Hunt', reflection_prompt: 'Reflect on how completing "Sensory Scavenger Hunt" helped you. Spend 20 minutes actively noticing 5 distinct sights, sounds, and textures in your immediate environment without using a screen. This helps ground you in the present moment.', target_archetype: 'Mind Wanderer' },
    { id: 'be59195a-f802-4ef9-9bde-dd3fd952e653', content: 'Outdoor Observation Challenge', reflection_prompt: 'Reflect on how completing "Outdoor Observation Challenge" helped you. Spend 20 minutes outdoors, actively observing your surroundings. Pay attention to sounds, smells, textures, and visual details you might usually overlook. Try to identify three new things you\'ve never noticed before in your immediate environment.', target_archetype: 'Mind Wanderer' },
    { id: '019eb6b7-e184-468a-927e-971e45ab8e37', content: 'One-Page Story Spark', reflection_prompt: 'Reflect on how completing "One-Page Story Spark" helped you. Choose a random object in your environment and spend 15 minutes writing a very short, imaginative story about it. Don\'t worry about perfection, just let your creativity flow. This channels your mind-wandering into a productive, non-digital outlet.', target_archetype: 'Mind Wanderer' },
    { id: '618bc8d7-f350-450d-9920-96892e0e4cd3', content: 'Nature\'s Glimpse Challenge', reflection_prompt: 'Reflect on how completing "Nature\'s Glimpse Challenge" helped you. Step outside or look out a window for 5 minutes. Find one natural element (a cloud, a tree, a bird) and observe it without judgment or distraction. No photos, just pure observation.', target_archetype: 'Mind Wanderer' },
    { id: '9326ed82-3870-4ad9-91c5-c5c68cecba00', content: 'Visual Zen: Desktop Declutter', reflection_prompt: 'Reflect on how completing "Visual Zen: Desktop Declutter" helped you. Dedicate 10 minutes to decluttering your computer desktop. Delete unnecessary files, organize icons into folders, and set a calming, non-distracting background. This small step can reduce digital overwhelm.', target_archetype: 'Mind Wanderer' },
    { id: 'eeed32c9-e5d8-4aad-bbb5-9db2da27fa1a', content: 'Offline Inspiration Hunt', reflection_prompt: 'Reflect on how completing "Offline Inspiration Hunt" helped you. Spend 20 minutes actively seeking inspiration away from screens. This could involve browsing a physical book, sketching, observing nature from a window, or listening to music without visual distractions. The goal is to stimulate creativity offline.', target_archetype: 'Mind Wanderer' },
    { id: '527acb84-4350-4a85-ab47-73b2ea0ececc', content: 'The 25-Minute Focus Sprint', reflection_prompt: 'Reflect on how completing "The 25-Minute Focus Sprint" helped you. Utilize the Pomodoro Technique to dedicate 25 minutes of uninterrupted, focused work on a single task. Set a timer, eliminate distractions, and then take a short 5-minute break. This builds focused concentration.', target_archetype: 'Balanced Thinker' },
    { id: 'ce2b138a-340e-4ce4-9de5-d6af8aa7391d', content: 'Screen-Free Creative Spark', reflection_prompt: 'Reflect on how completing "Screen-Free Creative Spark" helped you. Dedicate 30 minutes to a creative activity completely free of screens – sketch, write in a physical journal, or play an instrument. This helps to shift focus away from digital stimuli and engage different parts of your brain.', target_archetype: 'Focus Initiator' },
    { id: 'eca1c413-7538-4f1f-904f-e2e926e5f326', content: 'Mindful Morning Stretch', reflection_prompt: 'Reflect on how completing "Mindful Morning Stretch" helped you. Start your day with a gentle 5-minute stretch routine. Focus on your breath and how your body feels, letting go of any thoughts about the day ahead. This helps ground you before screen time.', target_archetype: 'Mind Wanderer' },
    { id: 'df598e78-c916-4f58-a62c-8616d8cbdedc', content: 'Evening Gratitude Journal', reflection_prompt: 'Reflect on how completing "Evening Gratitude Journal" helped you. Before bed, take 5-10 minutes to write down 3-5 things you are grateful for from your day. This helps shift focus from screens to positive reflection and improves sleep quality.', target_archetype: 'Mind Wanderer' },
    { id: 'b87c33c8-1697-4a1b-a905-9bc0bacc7479', content: 'Complete a 15-minute focused work session (Pomodoro)', reflection_prompt: 'What did you work on and what did you accomplish?', target_archetype: 'Balanced Thinker' },
    { id: '782ea024-d608-4461-ae95-eede1315f84e', content: 'Practice a new skill for 20 minutes', reflection_prompt: 'What progress did you make today?', target_archetype: 'Focus Initiator' },
    { id: '5d72cfdb-8568-43ba-9668-c9db849a2c6c', content: 'Meditate or do breathing exercises for 5 minutes', reflection_prompt: 'How did this practice affect your mental state?', target_archetype: 'Focus Initiator' },
    { id: 'd9610a8c-3095-464d-b617-a9ce82384272', content: 'Create something (art, writing, music, code)', reflection_prompt: 'What inspired you to create this?', target_archetype: 'True Potential Seeker' },
    { id: '5cb4779c-21c8-4931-8f8f-069e93598385', content: 'Teach someone something you know', reflection_prompt: 'What did you teach and how did they respond?', target_archetype: 'True Potential Seeker' },
    { id: '08874f25-2077-465c-a421-a798b3f21382', content: 'Plan tomorrow\'s top 3 priorities', reflection_prompt: 'Why are these your top priorities?', target_archetype: 'True Potential Seeker' },
];

async function seedQuests() {
    console.log('🌱 Seeding quests to database...\n');
    console.log(`Total quests to insert: ${quests.length}`);

    // First, check if quests table exists and has data
    const { count } = await supabase.from('quests').select('*', { count: 'exact', head: true });
    console.log(`Existing quests in database: ${count || 0}`);

    // Insert quests in batches
    const batchSize = 50;
    let inserted = 0;
    let errors = 0;

    for (let i = 0; i < quests.length; i += batchSize) {
        const batch = quests.slice(i, i + batchSize);

        const { data, error } = await supabase
            .from('quests')
            .upsert(batch, { onConflict: 'id' });

        if (error) {
            console.error(`❌ Error inserting batch ${i / batchSize + 1}:`, error.message);
            errors++;
        } else {
            inserted += batch.length;
            console.log(`✅ Inserted batch ${i / batchSize + 1} (${batch.length} quests)`);
        }
    }

    console.log(`\n🎉 Seeding complete!`);
    console.log(`   Inserted: ${inserted} quests`);
    console.log(`   Errors: ${errors}`);
}

seedQuests();
